// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyC_7rMODRZDE-SACeweBr-O4Yc7tNuGk',
    appId: '1:761765698507:web:2419e9006416e9ef1db44e',
    messagingSenderId: '761765698507',
    projectId: 'hrms-1bc9a',
    authDomain: 'hrms-1bc9a.firebaseapp.com',
    storageBucket: 'hrms-1bc9a.firebasestorage.app',
    measurementId: 'G-0SFN6NBJH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9cfM_tk6aFaBJAMMRl7XAYKuAbEzkgSk',
    appId: '1:761765698507:android:8e36b23b6e4e63931db44e',
    messagingSenderId: '761765698507',
    projectId: 'hrms-1bc9a',
    storageBucket: 'hrms-1bc9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF6XJGmFR2-WPonudXLMJ9TY3EGW4TpoA',
    appId: '1:761765698507:ios:16462ce95f4fb20a1db44e',
    messagingSenderId: '761765698507',
    projectId: 'hrms-1bc9a',
    storageBucket: 'hrms-1bc9a.firebasestorage.app',
    iosBundleId: 'com.example.hrmsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF6XJGmFR2-WPonudXLMJ9TY3EGW4TpoA',
    appId: '1:761765698507:ios:16462ce95f4fb20a1db44e',
    messagingSenderId: '761765698507',
    projectId: 'hrms-1bc9a',
    storageBucket: 'hrms-1bc9a.firebasestorage.app',
    iosBundleId: 'com.example.hrmsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyC_7rMODRZDE-SACeweBr-O4Yc7tNuGk',
    appId: '1:761765698507:web:7b1ce3a1fd9e929d1db44e',
    messagingSenderId: '761765698507',
    projectId: 'hrms-1bc9a',
    authDomain: 'hrms-1bc9a.firebaseapp.com',
    storageBucket: 'hrms-1bc9a.firebasestorage.app',
    measurementId: 'G-Z6CM8KQTMT',
  );

}